const { UIBuilder } = require("../scripts/msw_ui_builder.cjs");
const b = UIBuilder.read("C:/Users/yaong/Documents/메이플월드/ui/HUDGroup.ui");
console.log("ResourcePanel present?", !!b.find("/ui/HUDGroup/ResourcePanel"));
console.log("Minimap present?", !!b.find("/ui/HUDGroup/Minimap"));
console.log("Minimap has UIMinimapController?", b.hasComponent("/ui/HUDGroup/Minimap", "script.UIMinimapController"));
console.log("Cell_0_0?", !!b.find("/ui/HUDGroup/Minimap/Cell_0_0"));
console.log("Cell_14_14?", !!b.find("/ui/HUDGroup/Minimap/Cell_14_14"));
console.log("Marker?", !!b.find("/ui/HUDGroup/Minimap/Marker"));
const cells = b.listEntities().filter(e => e.path.includes("/Minimap/Cell_")).length;
console.log("cell count:", cells);
